[package]
name = "gui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ollejer-chess = {path = "../ollejer-chess"}
ggez = "0.6.1"
glam = { version = "0.17.3", features = ["mint"]}